### ISSUE TITLE
Se borran los datos del producto

### ISSUE THREAD

**Issue by NexusMTO** [jmaister/orderproject#2]
Al editar una factura, los datos de los productos tanto precio y cantidad impuesto y subtotal desaparecen, al parecer por la funcion update_all(); en /static/js/invoice.js  linea 86 y 134

**Comment by jmaister** [comment]
La librería Globalize que se encarga del formato de números no se carga bien.

**Comment by jmaister** [comment]
Arreglado, ahora se cargan todas las Cultures de Globalize.
